# Generated by Django 5.0.4 on 2024-04-20 05:12

import django.db.models.deletion
import smartui.medicals.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecords',
            name='doctor_consent_for_external_provider',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalrecords',
            name='to_be_reviewed_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='to_be_reviewed_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalrecords',
            name='user_consent_for_external_provider',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='medicalrecords',
            name='medical_report_file',
            field=models.FileField(blank=True, upload_to=smartui.medicals.models.medical_files_upload_location),
        ),
        migrations.CreateModel(
            name='ExternalProviders',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('provider_name', models.CharField(max_length=100, unique=True)),
                ('location', models.TextField()),
                ('description', models.TextField()),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalProviderStaff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('external_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_providers', to='medicals.externalproviders')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalRecordForExternalProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('external_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicals.externalproviders')),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicals.medicalrecords')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
